site_name: PyHades Documentation

theme:
  name: material

repo_name: Hades
repo_url: https://github.com/know-ai/hades
edit_uri: ""
site_dir: _build/html

nav:
    - Summary: 'index.md'
    - User Guide:
      - State Machines: 'user_guide_state_machines.md'
      - Web Frameworks Integration: 'user_guide_context.md'
      - Current Value Table (CVT): 'user_guide_cvt.md'
    - API Reference:
      - PyHades: 'api_core.md'
      - PyHadesContext: 'api_context.md'
      - PyHadesStateMachine: 'api_state_machine.md'
      - StateMachineManager: 'api_state_machine_manager.md'
      - Models: 'api_models.md'
      - CVT: 'api_cvt.md'

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
  - pymdownx.arithmatex:
      generic: true

extra_css:
    - css/custom.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js